controller_list:

  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory

    default: true
    joints:
      - shoulder_stevo_to_axis
      - shoulder_stevo_lift_to_axis
      - big_arm_up_to_axis
      - small_arm_up_to_axis
      - wrist_run_stevo_to_axis
      - hand_run_stevo_to_hand_run_stevo_axis